[HAR-9445]: Always retry on AWSKMSException. (#5818)
* [HAR-9445]: Always retry on AWSKMSException.

The root cause exception is thrown from AWSKMSClient (407 is a proxy authorization issue), assumably a temporary AWS issue. We should always retry on AWSKMSException!
com.amazonaws.services.kms.model.AWSKMSException: null (Service: AWSKMS; Status Code: 407; Error Code: null; Request ID: null)

* [HAR-9445]: Fixing the unit test failure.

* [HAR-9445]: Merge remote-tracking branch 'origin/master' into HAR-9445_retry_on_all_kmsclient_exception

* [HAR-9445]: Merge remote-tracking branch 'origin/master' into HAR-9445_retry_on_all_kmsclient_exception

* [HAR-9445]: Merge with master.