[PL-1296]: set `useIndividualEmails` flag true for Account Administrator user groups (#6529)
* [PL-1296]: set `useIndividualEmails` flag true for Account Administrator user groups

* add logs

* use bulk write to update user groups

* revert bulk write, use WingsPersistence#save instead of userGroupService#save since the latter does additional work than what we need

reverting bulk write because it gives this error:
```
2019-04-09 14:03:13,131 [pool-5-thread-4] ERROR  migrations.all.SetEmailToIndividualMemberFlag - Error running SetEmailToIndividualMemberFlag migration
org.bson.codecs.configuration.CodecConfigurationException: Can't find a codec for class software.wings.beans.notification.SlackNotificationSetting.
```