Har 2346 2018 05 19 2100 (#1904)
* HAR-2364 Cloud formation support with states

* HAR-2364 Cloud formation support with states

* Change CreateStack to UpsertStack logic

* Change CreateStack to UpsertStack logic

* HAR-2364 More debugging with Anubhaw and Adwait

* Changes for Log

* HAR-2346 Printing AWS stack events

* HAR-2346 Printing AWS stack events

* HAR-2346 Printing AWS stack events

* HAR-2346 Printing AWS stack events

* HAR-2346 Printing AWS stack events

* HAR-2346 Printing AWS stack events

* Include cluster role binding by default (#1903)

* Include cluster role binding by default

* simplify readme

* don't install nano

* simplify more

* Delegate Task ID should not be copied to the next stateExecutionInstance (#1860)

* mirgation to add group names in metric collections (#1905)

* mirgation to add group names in metric collections

* add defualt group name to analysis

* test fix

* add group name to unique index (#1907)

* migrate learning engine analysis task (#1908)

* migrate learning engine analysis task

* Add group id to the collection

* fix field name

* add default value for group name

* add test to imporve coverage

* checkstyle fix

* add group name index to learning engine tasks (#1909)

* changes for appdynamics dependent tiers (#1834)

* removed anom cluster labels

* set appid for apm data collection

* APPD PCF

* metric analysis with pcf

* dependent tier changes

* collect metric for dependent tiers

* moved file from another branch to this one

* analysis for multiple groups

* moved files

* for predictive time series analysis always use ML

* decide anlysis based on ts analysis type task

* decide anlysis based on ts analysis type task

* clean up

* made the output data compatible

* added new param to parser

* fixed unittest

* fix typo

* clean up

* added max risk to result of predictive

* fix for predictive

* added host name to analysis result

* removed todo

* send test data back for debugging purposes

* commented test fun from timeseriesML

* check if test data is valid

* check if test data is valid

* more fixes

* clean up

* fixed a bug

* skip metrics that throughput is less than rpm

* Fix to not pre terminate analysis

* removed both side outliers from next time prediction

* adjust deployment index based on analysis start min

* added degree of freedom to estimate variance

* fix for multiple response, per group name

* set std to 0 when it is nan

* added 99 percentile to cal risk

* add dependency path

* add dependency path as an extra field

* added unittest for predictio analysis

* returnin group name with analysis result

* removed groupname

* fix for state

* more fixes

* test fixes

* fix tests

* make tier dependency call parallel

* test fixes

* bug fix + test

* checkstyle + integration test fix

* compilation fix

* add default group name for other APM providers (#1912)

* Use X-Forwarded-For to get real client IP when in a cluster (#1915)

* User should be able to edit the service variable name (#1913)

* Fixed the parameters (#1911)

* Adding TestWinRmConnection functionality (#1892)

* Fix for NPE (#1866)

* Changing the alerts to warnings in some cases (#1917)

* Changing the alerts to warnings in some cases

* Sorting support accounts

* formatting

* Registering class NoClassDefFoundError with kryo (#1920)

* Fix alert noise for workflow execution without state (#1921)

* Fix alert noise for workflow execution without state

* Demo hacks (#1835)

* Demo hacks

* fix tests

* fix unit tests

* integration tests

* start up checks

* fix check style

* remove feature flag tests

* checkstyle

* fix integration tests

* xyz

* bump up coverage threshold (#1910)

* change to see current coverage level

* bump up the coverage threshold

* Terrafrom secret vars (#1919)

* Get destroy variables from the last provisioner (#1924)

* Get destroy variables from the last provisioner

* Failing SteadyStateCheck if no controllers are found with given Labels (#1923)

* Not serializing NULL values for K8 CLUSTER config (#1922)

* Fix command names (#1926)

* Fix command names

* Add tests

* HAR-2364 Some more code review comments